# Generated by Django 3.2.13 on 2022-06-02 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20220530_1640'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobId',
            new_name='Job',
        ),
        migrations.RemoveField(
            model_name='report',
            name='JobId',
        ),
        migrations.AddField(
            model_name='report',
            name='job',
            field=models.ManyToManyField(to='core.Job'),
        ),
    ]
