# Generated by Django 3.2.13 on 2022-06-08 08:10

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='image',
            field=models.ImageField(null=True, upload_to=core.models.report_image_file_path),
        ),
        migrations.DeleteModel(
            name='Locations',
        ),
    ]
