# Generated by Django 3.2.13 on 2022-06-09 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_locations'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='client_logo',
        ),
        migrations.RemoveField(
            model_name='report',
            name='month',
        ),
        migrations.RemoveField(
            model_name='report',
            name='year',
        ),
        migrations.AddField(
            model_name='report',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='clients',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.clients'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.locations'),
        ),
    ]
